In [ ]:
import os
os.system('pip install git+https://github.com/tikendraw/funcyou.git')

0

In [ ]:
from  funcyou.utils import printt

In [ ]:
import torch 

In [ ]:
scaler = torch.tensor(4)
scaler

tensor(4)

## Scaler

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()

4

## Vector

In [ ]:
vector = torch.tensor([[3,4,5]])
vector, vector.ndim, vector.shape


(tensor([[3, 4, 5]]), 2, torch.Size([1, 3]))

# Ramdom tensor

In [ ]:

randtens = torch.rand(size = (3,4))
randtens, randtens.shape, randtens.ndim

(tensor([[0.1941, 0.9740, 0.3925, 0.9387],
         [0.7978, 0.2667, 0.1264, 0.8788],
         [0.0096, 0.8513, 0.7045, 0.8817]]),
 torch.Size([3, 4]),
 2)

## Zeros. and Ones

In [ ]:
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero.shape, zero.ndim

(torch.Size([3, 4]), 2)

In [ ]:
zero * randtens

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(size = (3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.shape, one.ndim

(torch.Size([3, 4]), 2)

In [ ]:
one * randtens

tensor([[0.1941, 0.9740, 0.3925, 0.9387],
        [0.7978, 0.2667, 0.1264, 0.8788],
        [0.0096, 0.8513, 0.7045, 0.8817]])

## tensor range

In [ ]:
rang = torch.arange(start = 0, end = 99, step = 8)
rang

tensor([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])

In [ ]:
rang.shape, rang.ndim

(torch.Size([13]), 1)

In [ ]:
rang_zero = torch.zeros_like(input=rang)
rang_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## tensor Dtypes

In [ ]:
randtens.dtype

torch.float32

In [ ]:
rand16 = randtens.type(torch.half)
rand16

tensor([[0.1941, 0.9741, 0.3926, 0.9385],
        [0.7979, 0.2666, 0.1263, 0.8789],
        [0.0096, 0.8511, 0.7046, 0.8818]], dtype=torch.float16)

In [ ]:
randbig =   randtens.type(torch.double)
randbig

tensor([[0.1941, 0.9740, 0.3925, 0.9387],
        [0.7978, 0.2667, 0.1264, 0.8788],
        [0.0096, 0.8513, 0.7045, 0.8817]], dtype=torch.float64)

In [ ]:
randbig+rand16 == randtens*2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
display(randbig+rand16, randtens*2)

tensor([[0.3882, 1.9481, 0.7851, 1.8771],
        [1.5957, 0.5333, 0.2527, 1.7577],
        [0.0191, 1.7023, 1.4091, 1.7635]], dtype=torch.float64)

tensor([[0.3881, 1.9479, 0.7851, 1.8773],
        [1.5957, 0.5333, 0.2527, 1.7575],
        [0.0191, 1.7026, 1.4090, 1.7634]])

In [ ]:
torch.equal(randbig+rand16, randtens*2)

False

due to difference in float precision they not equal to each other

In [ ]:
hello = 'hello'

# Tensor Manipulation

In [ ]:
a = torch.rand(3,4)
a

tensor([[0.0687, 0.0855, 0.1029, 0.1974],
        [0.1907, 0.0631, 0.5503, 0.0650],
        [0.0025, 0.2821, 0.8324, 0.6901]])

In [ ]:
b = torch.rand(3,4)
b

tensor([[0.6295, 0.8892, 0.6125, 0.4528],
        [0.4796, 0.5333, 0.0744, 0.1977],
        [0.7873, 0.7063, 0.6762, 0.7992]])

In [ ]:
a+b

tensor([[0.6982, 0.9748, 0.7154, 0.6502],
        [0.6703, 0.5964, 0.6247, 0.2628],
        [0.7898, 0.9884, 1.5086, 1.4893]])

In [ ]:
torch.add(a,b)

tensor([[0.6982, 0.9748, 0.7154, 0.6502],
        [0.6703, 0.5964, 0.6247, 0.2628],
        [0.7898, 0.9884, 1.5086, 1.4893]])

In [ ]:
torch.add(a,b) == a+b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
a+10

tensor([[10.0687, 10.0855, 10.1029, 10.1974],
        [10.1907, 10.0631, 10.5503, 10.0650],
        [10.0025, 10.2821, 10.8324, 10.6901]])

In [ ]:
#subtraction
a-b, torch.subtract(a,b)

(tensor([[-0.5608, -0.8037, -0.5096, -0.2553],
         [-0.2890, -0.4702,  0.4759, -0.1327],
         [-0.7848, -0.4242,  0.1562, -0.1092]]),
 tensor([[-0.5608, -0.8037, -0.5096, -0.2553],
         [-0.2890, -0.4702,  0.4759, -0.1327],
         [-0.7848, -0.4242,  0.1562, -0.1092]]))

In [ ]:
a-b== torch.subtract(a,b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
a - 1

tensor([[-0.9313, -0.9145, -0.8971, -0.8026],
        [-0.8093, -0.9369, -0.4497, -0.9350],
        [-0.9975, -0.7179, -0.1676, -0.3099]])

In [ ]:
# DIVIsion
a/b , torch.divide(a,b)

(tensor([[1.0915e-01, 9.6183e-02, 1.6804e-01, 4.3605e-01],
         [3.9757e-01, 1.1827e-01, 7.3957e+00, 3.2887e-01],
         [3.1566e-03, 3.9939e-01, 1.2310e+00, 8.6338e-01]]),
 tensor([[1.0915e-01, 9.6183e-02, 1.6804e-01, 4.3605e-01],
         [3.9757e-01, 1.1827e-01, 7.3957e+00, 3.2887e-01],
         [3.1566e-03, 3.9939e-01, 1.2310e+00, 8.6338e-01]]))

In [ ]:
a/b == torch.divide(a,b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
a/2, b/2

(tensor([[0.0344, 0.0428, 0.0515, 0.0987],
         [0.0953, 0.0315, 0.2752, 0.0325],
         [0.0012, 0.1410, 0.4162, 0.3450]]),
 tensor([[0.3148, 0.4446, 0.3063, 0.2264],
         [0.2398, 0.2666, 0.0372, 0.0989],
         [0.3936, 0.3531, 0.3381, 0.3996]]))

In [ ]:
2*(a/2)== a

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# MUltiplication element wise


In [ ]:
a*b, torch.mul(a,b)

(tensor([[0.0433, 0.0761, 0.0630, 0.0894],
         [0.0915, 0.0336, 0.0410, 0.0129],
         [0.0020, 0.1992, 0.5629, 0.5515]]),
 tensor([[0.0433, 0.0761, 0.0630, 0.0894],
         [0.0915, 0.0336, 0.0410, 0.0129],
         [0.0020, 0.1992, 0.5629, 0.5515]]))

In [ ]:

a*b == torch.mul(a,b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
printt(a*3,a, terminal_width=180)

tensor([[0.2061, 0.2566, 0.3088, 0.5923],                                                 tensor([[0.0687, 0.0855, 0.1029, 0.1974],                                               
        [0.5721, 0.1892, 1.6510, 0.1951],                                                         [0.1907, 0.0631, 0.5503, 0.0650],                                               
        [0.0075, 0.8462, 2.4973, 2.0702]])                                                        [0.0025, 0.2821, 0.8324, 0.6901]])                                              


In [ ]:
pri = lambda *args: printt(*args, terminal_width=200)

In [ ]:
pri(a, a* 2)

tensor([[0.0895, 0.4561, 0.4857, 0.9085],                                                           tensor([[0.1790, 0.9123, 0.9714, 1.8169],                                                         
        [0.0490, 0.5943, 0.2040, 0.5391],                                                                   [0.0979, 1.1886, 0.4081, 1.0781],                                                         
        [0.2014, 0.9370, 0.2828, 0.7121]])                                                                  [0.4028, 1.8740, 0.5656, 1.4241]])                                                        


# Matrix Multiplication 

In [ ]:
a = torch.rand(3,4)
b = torch.rand(3,5)
c = torch.rand(4,5)a @ b # (3,4) @ (3, 5)
d = torch.rand(1,3)

In [ ]:
pri(a,b,c, d)

tensor([[0.3071, 0.4997, 0.2975, 0.8151],         tensor([[0.1069, 0.6136, 0.9422, 0.4888, 0.2507], tensor([[8.0826e-01, 8.3828e-01, 3.6253e-01, 3.39 tensor([[0.1245, 0.5240, 0.9474]])              
        [0.7720, 0.1825, 0.9383, 0.0592],                 [0.7608, 0.0427, 0.2536, 0.1850, 0.7987],         [8.3191e-01, 5.8199e-01, 4.7200e-01, 2.21                                                 
        [0.2922, 0.1295, 0.3330, 0.5167]])                [0.4442, 0.6847, 0.9757, 0.6958, 0.4524]]         [6.0603e-01, 8.1394e-01, 9.2133e-01, 6.54                                                 
                                                                                                            [7.7766e-04, 4.4921e-01, 2.7242e-01, 8.47                                                 


In [ ]:
a @ b # (3,4) @ (3, 5)

RuntimeError: ignored

In [ ]:
a @ c # (3,4) @ (4, 5)

tensor([[1.0331, 1.0318, 0.3611, 0.5425, 0.2180],
        [1.2590, 0.9324, 1.1410, 0.6152, 0.9005],
        [1.6581, 1.1452, 1.6128, 0.8691, 1.1834]])

In [ ]:
c @ b # (4,5) @ (3, 5)

RuntimeError: ignored

In [ ]:
c @ b.T # (4,5) @ (3, 5).T

tensor([[0.7098, 1.2765, 0.8024],
        [0.9893, 1.3023, 1.1896],
        [1.0679, 1.6918, 0.9036],
        [1.6475, 1.4442, 1.4534]])

In [ ]:
a.T @ d.T

tensor([[0.7196],
        [0.2805],
        [0.8442],
        [0.6220]])

In [ ]:
pri(a.T, d)

tensor([[0.3071, 0.7720, 0.2922],                                                                   tensor([[0.1245, 0.5240, 0.9474]])                                                                
        [0.4997, 0.1825, 0.1295],                                                                                                                                                                     
        [0.2975, 0.9383, 0.3330],                                                                                                                                                                     
        [0.8151, 0.0592, 0.5167]])                                                                                                                                                                    


In [ ]:
for i  in a.T:
    print(i * d , '--->', torch.sum(i*d, axis =-1))

print()
print('a.T @ d.T : \n', a.T @ d.T)

tensor([[0.0382, 0.4045, 0.2768]]) ---> tensor([0.7196])
tensor([[0.0622, 0.0956, 0.1227]]) ---> tensor([0.2805])
tensor([[0.0370, 0.4917, 0.3155]]) ---> tensor([0.8442])
tensor([[0.1015, 0.0310, 0.4895]]) ---> tensor([0.6220])

a.T @ d.T : 
 tensor([[0.7196],
        [0.2805],
        [0.8442],
        [0.6220]])


In [ ]:
# slicing

In [ ]:
a

tensor([[0.3071, 0.4997, 0.2975, 0.8151],
        [0.7720, 0.1825, 0.9383, 0.0592],
        [0.2922, 0.1295, 0.3330, 0.5167]])

In [ ]:
a[2]

tensor([0.2922, 0.1295, 0.3330, 0.5167])

# RESHAPe, VIEW, STACK

In [ ]:
reshape_a = a.reshape(2,-1)
reshape_a

tensor([[0.3071, 0.4997, 0.2975, 0.8151, 0.7720, 0.1825],
        [0.9383, 0.0592, 0.2922, 0.1295, 0.3330, 0.5167]])

In [ ]:
reshape_a[:,1] = 99

In [ ]:
pri(reshape_a, a)

tensor([[ 0.3071, 99.0000,  0.2975,  0.8151,  0.7720,  0.1825],                                     tensor([[ 0.3071, 99.0000,  0.2975,  0.8151],                                                     
        [ 0.9383, 99.0000,  0.2922,  0.1295,  0.3330,  0.5167]])                                            [ 0.7720,  0.1825,  0.9383, 99.0000],                                                     
                                                                                                            [ 0.2922,  0.1295,  0.3330,  0.5167]])                                                    


In [ ]:
#VIEW
a.shape

torch.Size([3, 4])

In [ ]:
aa = a.view(6,-1)
aa

tensor([[ 0.3071, 99.0000],
        [ 0.2975,  0.8151],
        [ 0.7720,  0.1825],
        [ 0.9383, 99.0000],
        [ 0.2922,  0.1295],
        [ 0.3330,  0.5167]])

In [ ]:
aa[3,:] = 44

In [ ]:
pri(aa, a, reshape_a)

tensor([[ 0.3071, 99.0000],                                       tensor([[ 0.3071, 99.0000,  0.2975,  0.8151],                     tensor([[ 0.3071, 99.0000,  0.2975,  0.8151,  0.7720,  0.1825], 
        [ 0.2975,  0.8151],                                               [ 0.7720,  0.1825, 44.0000, 44.0000],                             [44.0000, 44.0000,  0.2922,  0.1295,  0.3330,  0.5167]])
        [ 0.7720,  0.1825],                                               [ 0.2922,  0.1295,  0.3330,  0.5167]])                                                                                    
        [44.0000, 44.0000],                                                                                                                                                                         
        [ 0.2922,  0.1295],                                                                                                                                                                         
        [ 0.333

## all varient tensor share the same memory. you change one you change all of them.

In [ ]:
## STACKING

In [ ]:
a = torch.arange(1,13).reshape(3,-1)
a

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
stacked = torch.stack([a,a,a], dim=0)
stacked, stacked.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]),
 torch.Size([3, 3, 4]))

In [ ]:
stacked2 = torch.stack([a,a,a], dim=1)
stacked2, stacked2.shape

(tensor([[[ 1,  2,  3,  4],
          [ 1,  2,  3,  4],
          [ 1,  2,  3,  4]],
 
         [[ 5,  6,  7,  8],
          [ 5,  6,  7,  8],
          [ 5,  6,  7,  8]],
 
         [[ 9, 10, 11, 12],
          [ 9, 10, 11, 12],
          [ 9, 10, 11, 12]]]),
 torch.Size([3, 3, 4]))

In [ ]:
vstacked = torch.vstack([a,a,a])
vstacked, vstacked.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([9, 4]))

In [ ]:
hstacked = torch.hstack([a,a,a])
hstacked, hstacked.shape

(tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
         [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]]),
 torch.Size([3, 12]))

In [ ]:
vconcat = torch.concatenate([a,a,a], axis = 0)
vconcat, vconcat.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([9, 4]))

In [ ]:
hconcat = torch.concatenate([a,a,a], axis = -1)
hconcat, hconcat.shape

(tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
         [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]]),
 torch.Size([3, 12]))

In [ ]:
torch.equal(vstacked, vconcat)

True

In [ ]:
torch.equal(hstacked, hconcat)

True

`torch.vstack == torch.concatenate(axis = 0)`

`torch.hstack == torch.concatenate(axis = 1)`

# SQUEEZE , UNSQUEEZE, PERMUTE

In [ ]:
a = torch.rand(1,224,224,3)
a.shape

torch.Size([1, 224, 224, 3])

In [ ]:
sq_a = a.squeeze() # removes singular dimensions
sq_a.shape

torch.Size([224, 224, 3])

In [ ]:
unsq_a = sq_a.unsqueeze(dim = 0) # adds singular dimension on dim
unsq_a.shape

torch.Size([1, 224, 224, 3])

In [ ]:
per_a = a.permute(0, 3, 1, 2)  # rearranges dimensions in given specific orger here (batch, h, w, c) --> (batch, c, h, w)
per_a.shape

torch.Size([1, 3, 224, 224])

In [1]:
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# Randomly initialize weights
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    # y = a + b x + c x^2 + d x^3
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 179.11891996018844
199 124.65666561719183
299 87.70161521864736
399 62.59690795023541
499 45.52357994402288
599 33.899234468645005
699 25.975849800104793
799 20.568948953746176
899 16.87505931043464
999 14.348563659551495
1099 12.618538350842085
1199 11.432538564601685
1299 10.618560183518355
1399 10.059274154655293
1499 9.674555222099407
1599 9.409622114221774
1699 9.226978037205054
1799 9.100927620205887
1899 9.01384247455115
1999 8.953614822666356
Result: y = -0.01045425103312525 + 0.8506777469088217 x + 0.0018035322627021836 x^2 + -0.09246796640903883 x^3
